STO_server/urls.py
"""STO_server URL Configuration
The `urlpatterns` list routes URLs to views.
"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static

from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page

from STO_main.sitemap import StaticViewSitemap, DynamicCategoryViewSitemap, \
    DynamicStockViewSitemap, DynamicServiceViewSitemap, DynamicCaseViewSitemap
from STO_main.views import MainView, CategoryView, ServiceView, CaseView, CaseListView, StaffListView, \
    VideoReviewsListView, GuaranteeView, ContactUsView, StockView, StockListView, AddServiceToMyListView, \
    RemoveChosenService, AppointmentView, ServicesFilteredView, my_handler404, my_handler500, ReferralProgramView, \
    BonusProgramView, robots_txt

from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
    'category': DynamicCategoryViewSitemap,
    'services': DynamicServiceViewSitemap,
    'case': DynamicCaseViewSitemap,
    'stocks': DynamicStockViewSitemap,
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', robots_txt),

    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='index'),

    path('categories/<slug:category_slug>/', CategoryView.as_view(), name='category_read'),
    path('services/<slug:service_slug>/', ServiceView.as_view(), name='service_read'),
    path('service-add/<slug:slug>/', AddServiceToMyListView.as_view(), name='add_service_to_list'),
    path('service-remove/<slug:slug>/', RemoveChosenService.as_view(), name='remove_service_from_list'),
    path('services-registration/', AppointmentView.as_view(), name='services_registration'),
    path('search/', ServicesFilteredView.as_view(), name='search_services'),

    path('cases/<slug:case_slug>/', CaseView.as_view(), name='case_read'),
    path('cases/', CaseListView.as_view(), name='cases_list'),

    path('stocks/<slug:stock_slug>/', StockView.as_view(), name='stock_detail'),
    path('stocks/', cache_page(60)(StockListView.as_view()), name='stocks_list'),
    # path('stocks/', StockListView.as_view(), name='stocks_list'),
    path('referral/', ReferralProgramView.as_view(), name='referral'),
    path('bonus/', BonusProgramView.as_view(), name='bonus'),

    path('about/', StaffListView.as_view(), name='about'),
    # path('reviews/', VideoReviewsListView.as_view(), name='reviews'),
    path('reviews/', cache_page(60)(VideoReviewsListView.as_view()), name='reviews'),
    path('guarantees/', GuaranteeView.as_view(), name='guarantees'),
    path('contacts/', ContactUsView.as_view(), name='contacts'),
]

handler404 = 'STO_main.views.my_handler404'
handler500 = 'STO_main.views.my_handler500'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]
    urlpatterns += [path('404/', my_handler404, kwargs={'exception': Exception('Page not found')}, name='page_404')]
    urlpatterns += [path('500/', my_handler500, kwargs={'exception': Exception('Internal server error')},
                         name='page_500')]

STO_main/models.py
"""
Contains the models required to ensure the operation of the main logic of the project.
"""

import logging
from datetime import datetime
from logging import Logger
from django.db import IntegrityError

from PIL import Image
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import localdate
from embed_video.fields import EmbedVideoField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from phonenumber_field.modelfields import PhoneNumberField
from pytils.translit import slugify

logger: Logger = logging.getLogger(__name__)

# validator for vehicle VIN and license plates
alphanumeric = RegexValidator(r'^[0-9a-zA-ZА-Яа-я]*$',
                              'Допустимы только буквенно-цифровые значения.')


def form_image_path(instance, filename: str, folder: str = 'all') -> str:
    """Generates and returns the path for the saved images.
    It is necessary for the orderly storage of images.

    Args:

        * instance: an instance of an object being created or modified.
        * filename (`str`): the name under which the image will be stored.
        * folder (`str`): name of the folder where the image will be placed.

    Returns:

        * str: the path to the saved file.
    """
    folders = {Case: 'case_images', Category: 'cat_images',
               Stock: 'stock_images', STOStaff: 'staff_images'}
    try:
        title_str = instance.title.replace(' ', '_')
        if type(instance) == Service:
            return f'service_images/{instance.category}/{title_str}_{filename}'
        folder = folders[type(instance)]
        return f'{folder}/{title_str}_{filename}'
    except AttributeError:
        try:
            folder = folders[type(instance)]
            return f'{folder}/{instance.first_name}_{instance.last_name}_{filename}'
        except Exception as error:
            logger.error('Error when forming the path to save the image %s'
                         'when %s creating.\n%s', filename, instance, error)
    except Exception as error:
        logger.error('Error when forming the path to save the image %s'
                     'when %s creating.\n%s', filename, instance, error)
    return f'{folder}/error_path/{filename}'


def image_processing(image, max_width: int, max_height: int):
    """Reduces images to a required size, if they exceed it.

    Args:

        * image: contents of the image field of instance.
        * max_width (`int`): set maximum width.
        * max_height (`int`): set maximum height.
    """
    img = Image.open(image.path)

    if img.height > max_width or img.width > max_height:
        output_size = (max_width, max_height)
        img.thumbnail(output_size)
        img.save(image.path)


class BaseService(models.Model):
    """Base class for Category, Service, Case, VideoFile and Stock models"""
    seo_title = models.CharField(max_length=200, blank=True, verbose_name='SEO title')
    seo_description = models.CharField(max_length=250, blank=True, verbose_name='SEO description')
    h1 = models.CharField(max_length=150, blank=True, verbose_name='H1 тэг')

    title = models.CharField(max_length=150, unique=True, verbose_name='наименование')
    create_time = models.DateTimeField(default=timezone.now, verbose_name="время создания")
    update_time = models.DateTimeField(default=timezone.now, verbose_name="время изменения")
    is_active = models.BooleanField(default=True, db_index=True, verbose_name="активен")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        """Specifying an abstract class."""
        abstract = True

    def __str__(self):
        """Forms and returns a printable representation of the object.
        """
        return str(self.title)

    def save(self, *args, slugified_field=None, **kwargs):
        """Automatic filling in 'update_time' and 'slug' fields when saving."""
        self.update_time = timezone.now()
        if slugified_field:
            try:
                with transaction.atomic():
                    self.slug = old_slug = slugify(slugified_field)
                    super().save(*args, **kwargs)
            except IntegrityError:
                with transaction.atomic():
                    self.slug = slugify(slugified_field + str(timezone.now()))
                    logger.info('Non-unique slug %s replaced with %s', old_slug, self.slug)
                    super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)

    def get_absolute_url(self, urlpattern_name: str):
        """Returns formed url for the object."""
        return reverse(urlpattern_name, args=[str(self.slug)])


class Category(BaseService, MPTTModel):
    """The model for the category."""
    description = models.TextField(verbose_name="описание", blank=True, max_length=1500)
    image = models.ImageField(verbose_name="картинка", upload_to=form_image_path, blank=True)
    parent = TreeForeignKey('self', on_delete=models.PROTECT, null=True, blank=True,
                            related_name='children', db_index=True,
                            verbose_name='родительская категория')

    class MPTTMeta:
        """Ordering objects by their title."""
        order_insertion_by = ['title']

    class Meta:
        """Ordering categories according to their id. Defining the uniqueness condition."""
        unique_together = [['parent', 'slug']]
        ordering = ('id',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def save(self, *args, **kwargs):
        """Automatic filling in update_time and the slug field when saving,
        as well as image processing.
        Automatic activation/deactivation of child categories and services when
        activating/deactivating a category.
        """
        super().save(*args, slugified_field=self.title, **kwargs)
        if self.image:
            image_processing(self.image, 240, 240)
        for item in self.get_children():
            self.child_repeat_after_parent(item, self)
            for service in item.service_set.all():
                self.child_repeat_after_parent(service, item)
        for service in self.service_set.all():
            self.child_repeat_after_parent(service, self)

    @staticmethod
    def child_repeat_after_parent(child, parent):
        child.is_active = False if parent.is_active is False else True
        child.save()

    def get_absolute_url(self, urlpattern_name='category_read'):
        """Returns formed url for the object."""
        return super().get_absolute_url(urlpattern_name=urlpattern_name)


class Service(BaseService):
    """The model for the service."""
    body = models.TextField(verbose_name="описание услуги")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категория", default='1')
    image = models.ImageField(upload_to=form_image_path, blank=True, verbose_name="картинка")
    min_price = models.DecimalField(max_digits=8, decimal_places=2,
                                    default=1500.00, verbose_name="мин. стоимость")
    max_price = models.DecimalField(max_digits=8, decimal_places=2,
                                    default=15000.00, verbose_name="макс. стоимость")

    class Meta:
        """Ordering services according to their title."""
        ordering = ('title',)
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def save(self, *args, **kwargs):
        """Automatic filling in update_time and the slug field when saving,
        as well as image processing."""
        super().save(*args, slugified_field=self.title, **kwargs)
        if self.image:
            image_processing(self.image, 240, 240)

    def get_absolute_url(self, urlpattern_name='service_read'):
        """Returns formed url for the object."""
        return super().get_absolute_url(urlpattern_name=urlpattern_name)


class Car(models.Model):
    """The model for the client's car."""
    brand = models.CharField(max_length=50, verbose_name='марка автомобиля')
    car_model = models.CharField(max_length=200, verbose_name='модель автомобиля')
    vin = models.CharField(max_length=17, blank=True, verbose_name='VIN автомобиля',
                           validators=[alphanumeric])
    release_year = models.PositiveSmallIntegerField(blank=True, default=2020,
                                                    verbose_name='год выпуска')
    licence_plate = models.CharField(max_length=10, blank=True,
                                     verbose_name='номера автомобиля', validators=[alphanumeric])
    description = models.CharField(max_length=200, blank=True,
                                   verbose_name='дополнительная информация об автомобиле')
    mileage = models.PositiveIntegerField(blank=True, null=True, verbose_name='пробег')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name="активен")
    create_time = models.DateTimeField(default=timezone.now, verbose_name="время создания")
    update_time = models.DateTimeField(default=timezone.now, verbose_name="время изменения")

    class Meta:
        """Ordering objects according to their update time.
        """
        ordering = ('update_time',)
        verbose_name = 'Автомобиль клиента'
        verbose_name_plural = 'Автомобили клиентов'

    def __str__(self):
        """Forms and returns a printable representation of the object.
        """
        return f'{self.brand} {self.car_model}'

    def save(self, *args, **kwargs):
        """Automatic filling in 'update_time' field when saving."""
        super().save(*args, **kwargs)
        self.update_time = timezone.now()


class Case(BaseService):
    """The model for the completed work case."""
    body = models.TextField(verbose_name='описание')

templates/cases/case-details.html
{% extends 'base_STO.html' %}
{% load static %}


{% block content %}
    <main>
        <!-- page__title-start -->
        {% include 'includes/page-title.html' %}
        <!-- page__title-end -->

        <!-- page content start -->
        <section class="blog-details-area mt-100 mb-50">
            <div class="container custom-container">
                <div class="row">
                    <div class="col-xl-8 col-lg-8">
                        <div class="row">
                            <div class="blog-wrapper pr-50">
                                <div class="blog-wrap blog-item mb-50">
                                    <div class="blog-thumb">
                                        <img src="{% if case.image_before %} {{ case.image_before.url }} {% else %} {% static 'assets/img/blog/blog-1.jpg' %} {% endif %}"
                                             alt="" id="{{ case.image_before.url }}" name="{{ case.image_after.url }}"
                                             class="case-images">
                                    </div>
                                    <div class="blog-details mt-35 text-main">
                                        <ul class="blog-meta">
                                            <li><h5>{{ case.end_date }}</h5></li>
                                            <li><h5>Срок выполнения: {{ case.period }} {{ case.period_to_days }}</h5>
                                            </li>
                                            </li>
                                        </ul>
                                        <h1 class="blog-title">
                                            {% if object.h1 %}{{ object.h1 }}
                                                {% else %}{{ object.title }}
                                            {% endif %}</h1>
                                        <div class="text-main">{{ object.body | safe }}</div>
                                    </div>
                                </div>
                                <div class="blog-info d-sm-flex align-items-center justify-content-between mb-40">
                                    <div class="blog-category">
                                        <span>Стоимость комплекса услуг: </span>
                                        <h3>{{ object.price }} &#x20bd;</h3>
                                    </div>
                                </div>

                                {% if object.videofile_set.all %}
                                    <div class="blog-wrapper pr-50">
                                        <div class="blog-wrap blog-item mb-50">
                                            <div class="blog-details mt-35 text-main">
                                                <h5>
                                                    Отзыв автовладельца:
                                                </h5>
                                            </div>
                                            <div class="blog-thumb">
                                                {% for review in object.videofile_set.all %}
                                                    <div class="thumb-wrap">
                                                        {% if review.video %}
                                                            <iframe width="560" height="315"
                                                                    class="embed-responsive-item d-flex"
                                                                    src="{{ review.video | safe }}"
                                                                    allowfullscreen></iframe>
                                                        {% endif %}
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4">
                        <div class="blog__sidebar">
                            {% if object.services %}
                                <div class="sidebar__widget sidebar__widget-padding mb-75 wow fadeInUp grey-bg-2"
                                     data-wow-delay=".6s"
                                     style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInUp;">
                                    <div class="sidebar__widget-title mb-25">
                                        <h4>Список услуг для этого заказа:</h4>
                                    </div>
                                    <div class="sidebar__widget-content">
                                        <div class="tags">
                                            <ul>
                                                {% for category in object.services.all %}
                                                    <li><a href="{{ category.get_absolute_url }}">
                                                        {{ category.title }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="sidebar__widget sidebar__widget-padding mb-50 wow fadeInUp grey-bg-2"
                                 data-wow-delay="1s">
                                <div class="sidebar__widget-title mb-15">
                                    <h4>Другие работы:</h4>
                                </div>
                                <div class="sidebar__widget-content">
                                    <div class="tags">
                                        <ul>
                                            {% for case in other_cases %}
                                                <li><a href="{{ case.get_absolute_url }}">
                                                    {{ case.title }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- page content end -->

    </main>

{% endblock %}

{% block js %}
    <script src="{% static 'assets/js/STO.js' %}"></script>
{% endblock %}

templates/cases/cases-list.html
{% extends 'base_STO.html' %}
{% load static %}


{% block content %}

    <main>
        <!-- page__title-start -->
        {% include 'includes/page-title.html' %}
        <!-- page__title-end -->

        <!-- page content start -->
        <section class="blog-area mt-30 mb-50">
            <div class="container custom-container">
                <div class="row">

                    <div class="col-12">
                        <h1 class="text-center mb-50">
                            Примеры отремонтированных машин на СТО «Кармастер» в Севастополе
                        </h1>
                        <div>
                            Примеры отремонтированных машин на СТО «Кармастер» в Севастополе
                        </div>
                    </div>

                    <!-- page left part start-->
                    <div class="col-xl-8 col-lg-8">
                        <div class="blog__wrapper pr-50">
                            {% for case in case_list %}
                                <div class="blog-wrap blog-item mb-50">
                                    <h3 class="blog-title">
                                        <a href="{{ case.get_absolute_url }}">{{ case.title }}</a>
                                    </h3>
                                    <div class="blog-thumb">
                                        <img src="{% if case.image_before %} {{ case.image_before.url }} {% else %} {% static 'assets/img/blog/blog-1.jpg' %} {% endif %}"
                                             alt="" id="{{ case.image_before.url }}" name="{{ case.image_after.url }}"
                                             class="case-images">
                                    </div>
                                    <div class="blog-details mt-35">
                                        <ul class="blog-meta">
                                            <li><h5>{{ case.end_date }}</h5></li>
                                            <li><h5>Срок выполнения: {{ case.period }} {{ case.period_to_days }}</h5>
                                            </li>
                                        </ul>
                                        <div class="text-main">{{ case.body | safe | truncatechars_html:200 }}</div>
                                        <div class="blog-btn mt-25">
                                            <a href="{{ case.get_absolute_url }}" class="link-btn">Узнать больше</a>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            {% endfor %}
                        </div>

                        <!-- pagination area start -->
                        <div class="row mb-50">
                            <div class="col-xxl-12">
                                <div class="shop-pagination">
                                    <div class="basic-pagination">
                                        <nav>
                                            <ul>
                                                <li>
                                                    <a class="{% if not page_obj.has_previous %} btn p-0 disabled {% endif %}"
                                                       href="{% if page_obj.has_previous %} ?page=
                                                   {{ page_obj.previous_page_number }}{% else %} # {% endif %}">
                                                        <i class="far fa-angle-left"></i>
                                                    </a>
                                                </li>
                                                {% for page in page_obj.paginator.page_range %}
                                                    <li>
                                                        <a href="?page={{ page }}">{{ page }}</a>
                                                    </li>
                                                {% endfor %}
                                                <li>
                                                    <a class="{% if not page_obj.has_next %} btn p-0 disabled {% endif %}"
                                                       href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                                               {% else %} # {% endif %}">
                                                        <i class="far fa-angle-right"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- pagination area end -->
                    </div>
                    <!-- page left part end-->

                    <!-- right sidebar start-->
                    <div class="col-xl-4 col-lg-4">
                        <div class="blog__sidebar">
                            <div class="sidebar__widget mb-50 wow fadeInUp" data-wow-delay=".2s"
                                 style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                                <div class="sidebar__widget-content">
                                    <div><h3>Записаться на СТО</h3></div>
                                    <div class="pro-cart-btn">
                                        <a href="{% url 'services_registration' %}" class="btn-tp-2 mb-20 m-1 w-100">
                                            К форме записи
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="sidebar__widget sidebar__widget-padding mb-75 wow fadeInUp grey-bg-2"
                                 data-wow-delay=".4s"
                                 style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
                                <div class="sidebar__widget-title mb-25">
                                    <h4>Больше выгоды</h4>
                                </div>
                                <div class="sidebar__widget-content">
                                    <div class="rc-post">
                                        <ul>
                                            <li class="d-flex align-items-center mb-20">
                                                <div class="rc-text text-main">
                                                    <a href="{% url 'stocks_list' %}">Акции</a>
                                                </div>
                                            </li>
                                            <li class="d-flex align-items-center mb-20">
                                                <div class="rc-text text-main">
                                                    <a href="{% url 'bonus' %}">Бонусная программа</a>
                                                </div>
                                            </li>
                                            <li class="d-flex align-items-center mb-20">
                                                <div class="rc-text text-main">
                                                    <a href="{% url 'referral' %}">Реферальная программа</a>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="sidebar__widget sidebar__widget-padding mb-75 wow fadeInUp grey-bg-2"
                                 data-wow-delay=".6s"
                                 style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInUp;">
                                <div class="sidebar__widget-title mb-25">
                                    <h4>Больше информации</h4>
                                </div>
                                <div class="sidebar__widget-content">
                                    <div class="rc-post">
                                        <ul>
                                            <li class="d-flex align-items-center mb-20">
                                                <div class="rc-text text-main">
                                                    <a href="{% url 'guarantees' %}">Гарантии</a>
                                                </div>
                                            </li>
                                            <li class="d-flex align-items-center mb-20">
                                                <div class="rc-text text-main">
                                                    <a href="{% url 'contacts' %}">Связаться с нами</a>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- page content end -->
    </main>

{% endblock %}

{% block js %}
    <script src="{% static 'assets/js/STO.js' %}"></script>
{% endblock %}